import React from "react";
import Head from "next/head";
import { Button, Box, Flex, Avatar } from "@chakra-ui/react";
import Link from "next/link";
function Menu() {
  return (
    <>
      <Head>
        <title>Sabrina Babakulova</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex m={4} justify="center" align="center" gap={5} mb={5}>
        <Link href="/Personal" passHref>
          <Flex flex={1} gap={2}>
            <Avatar
              name="Sabrina Babakulova"
              src="https://avatars.githubusercontent.com/u/63979168?v=4"
            />
            <Button
              variant="link"
              _focus={{
                boxShadow: "0px",
              }}
            >
              Sabrina&apos;s Personal
            </Button>
          </Flex>
        </Link>

        <Link href="/Blog" passHref>
          <Button
            variant="link"
            _focus={{
              boxShadow: "0px",
            }}
          >
            blog
          </Button>
        </Link>

        <Link href="/" passHref>
          <Button
            variant="link"
            _focus={{
              boxShadow: "0px",
            }}
          >
            go home
          </Button>
        </Link>
      </Flex>
    </>
  );
}

export default Menu;
