import React from "react";
import Head from "next/head";
import { Button, Flex } from "@chakra-ui/react";
import Link from "next/link";
import { useRouter } from "next/router";
import { signOut } from "next-auth/react";
function Menu() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        mt={4}
        justify="center"
        gap={5}
        direction={["column", "row"]}
        mb={5}
      >
        <Button
          onClick={async () => {
            router.push("/").then(() => signOut());
          }}
          flex={1}
          p={7}
          variant="solid"
        >
          Sign out
        </Button>

        <Link href="/Finances" passHref>
          <Button flex={3} variant="outline" p={7}>
            FINANCE MANAGEMENT
          </Button>
        </Link>

        <Link href="/" passHref>
          <Button flex={1} p={7}>
            GO HOME
          </Button>
        </Link>
      </Flex>
    </>
  );
}

export default Menu;
