import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useSession,  signOut  } from 'next-auth/react'
import SignIn from './components/SignIn'
import {Button} from '@chakra-ui/react';
import MainPage from './components/MainPage'

const Home: NextPage = () => {

  const { data: session } = useSession();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!session && <SignIn />}
      {session && <MainPage/>}
      {/* {!session && (<button onClick={()=>signIn()}>Sign in with github</button>)}
      {session && (<button onClick={()=>signOut()}>Sign out with github</button>)} */}
      
      {/* <main className={styles.main}>
      </main> */}

      <footer className={styles.footer}>
        {session && <Button onClick={() => signOut()} size="lg" mt={5} variant="outline">Sign out</Button>}
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
            
        </a>
      </footer>
    </div>
  )
}

export default Home
