import React from 'react'
import Head from 'next/head'
import { useSession, signOut } from 'next-auth/react'
import { Button, Flex, Center, Text } from '@chakra-ui/react';
import Link from 'next/link'
function Menu() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex mt={4} justify="center" gap={5} direction={["column", "row"]}>
        <Button onClick={() => signOut()} flex={1} p={7} variant="solid">Sign out</Button>

        <Link href="/components/InhaPage" passHref>
          <Button flex={3} variant="outline" p={7}>
            INHA STUFF
          </Button>
        </Link>
        <Link href="/components/FinancePage" passHref>
          <Button flex={3} variant="outline" p={7}>
            FINANCE MANAGEMENT
          </Button>
        </Link>

        <Link href="/" passHref>
          <Button flex={1} p={7}>
            GO HOME
          </Button></Link>
      </Flex>
    </>
  )
}

export default Menu